import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './Providers';
import { themes } from '@/helpers/Theme';
import Navbar from '@/components/Navbar';
import MobileMenu from '@/components/MobileMenu';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <style>
                    {themes.createTailwindThemeVariables([['dark', 'dark']])}
                </style>
            </head>
            <Providers>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} pt-12 antialiased h-screen w-screen bg-mainBG text-mainText`}
                >
                    <Navbar />
                    <MobileMenu />
                    {children}
                </body>
            </Providers>
        </html>
    );
}
